name: Android CI -> v1

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # untuk menyalin kode di repo ke Github Action
      - name: Checkout to specific branch
        uses: actions/checkout@v2.3.5
      
      - name: Setup JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 13.0.2
          distribution: 'zulu'
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        
      - name: Get Permission
        run: sudo chmod +x ./gradlew
          
      - name: Download dependencies
        run: ./gradlew androidDependencies
        
      - name: Run lint Test
        run: ./gradlew lint test
      
      - name: Run Test and Unit Test
        uses: doanpt/AndroidTestReportAction@v1.1
      
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: app
          path: app/build/outputs/apk/debug/app-debugg.apk
